services:
  - type: web
    name: AthenaLibrary
    env: dotnet
    branch: master
    buildCommand: "msbuild NhaSachMetMoi.sln /p:Configuration=Release"
    startCommand: "NhaSachMetMoi/NhaSachMetMoi.exe"
    plan: free
