services:
  - type: web
    name: AthenaLibrary
    env: dotnet
    branch: master
    buildCommand: "msbuild NhaSachMetMoi.sln /p:Configuration=Release"
    startCommand: "dotnet NhaSachMetMoi/bin/Release/NhaSachMetMoi.dll"
    plan: free
